(async function(){
'use strict';
const $=id=>document.getElementById(id), fields=['west','south','east','north'];
let map, drawing=false, start, catalog=[];
async function api(path='',data){const response=await fetch('/api/locations'+path,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'Request failed');return result;}
function message(value){$('message').textContent=value;}
function bounds(){return fields.map(id=>Number($(id).value));}
function button(label,action){const el=document.createElement('button');el.type='button';el.textContent=label;el.onclick=async()=>{el.disabled=true;try{await action();}catch(error){message(error.message);}finally{el.disabled=false;}};return el;}
async function updateBounds(value,fit=false){fields.forEach((id,i)=>$(id).value=value[i].toFixed(7));const [w,s,e,n]=value;if(map?.getSource('extent')){map.getSource('extent').setData({type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[[[w,s],[e,s],[e,n],[w,n],[w,s]]]}});if(fit)map.fitBounds([[w,s],[e,n]],{padding:65});}try{const estimate=await api('/estimate',{bounds:value,resolution:Number($('resolution').value)});$('estimate').textContent=`${estimate.widthMetres} × ${estimate.heightMetres} m · ${estimate.rasterCells.toLocaleString()} cells · ~${estimate.estimatedWorkingMemoryMB} MB working estimate${estimate.supported?'':' · Choose a smaller extent'}`;$('create-button').disabled=!estimate.supported;}catch(error){message(error.message);}}
map=new maplibregl.Map({container:'area-map',style:{version:8,sources:{base:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'base',type:'raster',source:'base'}]},center:[11.94,57.708],zoom:13});
map.addControl(new maplibregl.NavigationControl(),'bottom-right');
map.on('load',()=>{map.addSource('extent',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'extent-fill',type:'fill',source:'extent',paint:{'fill-color':'#b1e082','fill-opacity':.2}});map.addLayer({id:'extent-line',type:'line',source:'extent',paint:{'line-color':'#526c36','line-width':3}});updateBounds([11.9232,57.699,11.9568,57.717],true);});
$('draw').onclick=()=>{drawing=!drawing;start=null;$('draw').textContent=drawing?'Click two opposite corners':'Draw an extent';map.getCanvas().style.cursor=drawing?'crosshair':'';};
map.on('click',event=>{if(!drawing)return;if(!start){start=event.lngLat;return;}const end=event.lngLat;updateBounds([Math.min(start.lng,end.lng),Math.min(start.lat,end.lat),Math.max(start.lng,end.lng),Math.max(start.lat,end.lat)]);drawing=false;start=null;$('draw').textContent='Draw an extent';map.getCanvas().style.cursor='';});
fields.forEach(id=>$(id).onchange=()=>updateBounds(bounds()));$('resolution').onchange=()=>updateBounds(bounds());
$('title').oninput=()=>{if(!$('location-id').dataset.edited)$('location-id').value=$('title').value.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,64);};$('location-id').oninput=()=>$('location-id').dataset.edited='yes';
$('search').onsubmit=async event=>{event.preventDefault();try{const results=await api('/search?q='+encodeURIComponent($('place').value));$('search-results').replaceChildren(...results.map(item=>button(item.display_name,()=>{const lat=Number(item.lat),lng=Number(item.lon),dx=1000/(111320*Math.cos(lat*Math.PI/180)),dy=1000/111320;updateBounds([lng-dx,lat-dy,lng+dx,lat+dy],true);$('search-results').replaceChildren();})));if(!results.length)message('No Swedish place matched. You can also draw an extent.');}catch(error){message(error.message);}};
$('create').onsubmit=async event=>{event.preventDefault();try{const layers=[...document.querySelectorAll('#layers input:checked')].map(x=>x.value);if(layers.includes('thermal-comfort-btn')&&!$('study-date').value)throw Error('Choose a thermal study date, or deselect Comfort.');await api('',{id:$('location-id').value,title:$('title').value,bounds:bounds(),layers,resolution:Number($('resolution').value),studyDate:$('study-date').value||null});message('Location created. Configure connections, then select Generate.');await refresh();}catch(error){message(error.message);}};
async function sources(){const result=await api('/sources');$('source-status').replaceChildren(...Object.entries(result).map(([name,state])=>button(`${name}: ${state.configured?'configured · test':'not configured'}`,async()=>{const result=await api('/check-source',{source:name});message(`${name}: ${result.message}`);})));}
$('credentials').onsubmit=async event=>{event.preventDefault();const data={};for(const [name,value] of new FormData(event.target)){if(!value)continue;const [provider,key]=name.split('.');(data[provider]??={})[key]=value;}try{await api('/sources',data);event.target.reset();message('Connections saved locally. Use the test buttons to verify access.');await sources();}catch(error){message(error.message);}};
$('import').onsubmit=async event=>{event.preventDefault();try{await api('/import',{path:$('import-path').value});await refresh();message('Package imported and checksums verified.');}catch(error){message(error.message);}};
$('cancel').onclick=async()=>{try{await api('/cancel',{});await refresh();}catch(error){message(error.message);}};
async function refresh(){const result=await api();$('locations').replaceChildren(...result.locations.map(item=>{const card=document.createElement('article');card.className='location-card';const title=document.createElement('strong');title.textContent=item.title+(result.active?.id===item.id?' · active':'');const info=document.createElement('div');info.className='status';const caps=Object.values(item.capabilities||{});info.textContent=caps.length?`${caps.filter(x=>x.status==='ready').length} capabilities ready`:'Not yet generated';const actions=document.createElement('div');actions.className='actions';actions.append(button('Generate / resume',async()=>{await api('/generate',{id:item.id});await refresh();}),button('Validate',async()=>{const report=await api('/validate/'+item.id);message(JSON.stringify(report,null,2));}),button('Launch',async()=>{await api('/activate',{id:item.id});location.href='launcher.html';}),button('Export',async()=>{const out=await api('/export',{id:item.id});location.href=out.url;}));card.append(title,info,actions);return card;}));const job=result.job;$('job').textContent=job.state==='idle'?'':`${job.location}: ${job.state}\n${Object.entries(job.stages||{}).map(([name,state])=>`${name}: ${state.status}${state.cached?' (cached)':''}`).join('\n')}\n${job.message||''}`;$('cancel').hidden=!['queued','running'].includes(job.state);}
try{catalog=await api('/catalog');$('layers').replaceChildren(...catalog.filter(x=>!x.project).map(item=>{const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.value=item.id;input.checked=item.id!=='thermal-comfort-btn';label.append(input,document.createTextNode(item.name));return label;}));const doctor=await api('/doctor');$('environment').textContent=doctor.preparationReady?'Host ready':'Preparation dependencies need setup';await sources();await refresh();}catch(error){message(error.message);}
setInterval(()=>refresh().catch(error=>message(error.message)),3000);
})();
