/* Run with MR_PLAYWRIGHT pointing to a Playwright installation if it is not in node_modules. */
const {chromium}=require(process.env.MR_PLAYWRIGHT || 'playwright');
const fs=require('node:fs');
const assert=require('node:assert/strict');
const base=process.env.MR_TEST_URL || 'http://127.0.0.1:8091';
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:process.env.MR_BROWSER || undefined,args:['--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required','--disable-features=WebRtcHideLocalIpsWithMdns']});
  const desktop=await browser.newContext({viewport:{width:1440,height:900}}), page=await desktop.newPage();
  const memoryTransport=process.env.MR_TEST_TRANSPORT==='memory'?require('./session_test_transport.cjs')():null;
  if(memoryTransport)await memoryTransport(desktop);
  function trackPeers(){let constructor;window.__peers=[];Object.defineProperty(window,'Peer',{get(){return constructor;},set(value){constructor=new Proxy(value,{construct(target,args){const peer=Reflect.construct(target,args);window.__peers.push(peer);return peer;}});},configurable:true});}
  await page.addInitScript(trackPeers);
  const errors=[];page.on('pageerror',error=>{errors.push(error.message);console.log('HOST ERROR',error.message);});
  await page.goto(base+'/index.html',{waitUntil:'domcontentloaded'});
  await page.locator('#start-overlay').click();
  await page.waitForFunction(()=>window.MR_SESSION && window.MR_ADAPTER && window.map.loaded(),{timeout:60000});
  const summary=await page.evaluate(()=>new Promise(resolve=>{const channel=new BroadcastChannel('mr_session_admin');const timer=setInterval(()=>channel.postMessage({type:'admin-request'}),500);const timeout=setTimeout(()=>{clearInterval(timer);channel.close();resolve(null);},25000);channel.onmessage=({data})=>{if(data.type==='admin-state'&&data.invite){clearInterval(timer);clearTimeout(timeout);channel.close();resolve(data);}};}));
  console.log('Host session',summary?{peerStatus:summary.peerStatus,saveStatus:summary.saveStatus,services:summary.services}:'NO INVITATION');
  await page.screenshot({path:'.runtime/host.png'});
  if(!summary)throw Error('Host did not create an invitation');
  const invitation=new URL(summary.invite);const url=(process.env.MR_CLIENT_URL||base+'/session/client.html')+invitation.search;
  const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),phone=await mobile.newPage();
  if(memoryTransport)await memoryTransport(mobile);
  await phone.addInitScript(trackPeers);
  phone.on('pageerror',error=>{errors.push(error.message);console.log('PHONE ERROR',error.message);});
  phone.on('console',message=>{if(['warning','error'].includes(message.type()))console.log('PHONE CONSOLE',message.text().slice(0,300));});
  await phone.goto(url,{waitUntil:'domcontentloaded'});
  await phone.screenshot({path:'.runtime/phone-connect.png'});
  console.log('Phone loaded',await phone.locator('#connection').textContent());
  try {await phone.waitForFunction(()=>document.getElementById('connection').textContent.includes('Spectator'),null,{timeout:30000});}
  catch(error){
    const diagnostics=async()=>Promise.all(window.__peers.map(async p=>({open:p.open,disconnected:p.disconnected,connections:await Promise.all(Object.values(p.connections).flat().map(async c=>({open:c.open,ice:c.peerConnection?.iceConnectionState,connection:c.peerConnection?.connectionState,stats:c.peerConnection?[...await c.peerConnection.getStats()].map(([,v])=>v).filter(v=>['local-candidate','remote-candidate','candidate-pair'].includes(v.type)).map(v=>({type:v.type,state:v.state,candidateType:v.candidateType,protocol:v.protocol,requestsSent:v.requestsSent,responsesReceived:v.responsesReceived})):[]})))})));
    console.log('HOST PEERS',JSON.stringify(await page.evaluate(diagnostics)));console.log('PHONE PEERS',JSON.stringify(await phone.evaluate(diagnostics)));console.log('PHONE STATE',await phone.locator('body').innerText());await phone.screenshot({path:'.runtime/phone-failed.png'});await browser.close();throw error;}
  await phone.getByRole('button',{name:'Choose a controller slot',exact:true}).click();
  await phone.locator('#slots button').first().click();
  await phone.waitForFunction(()=>document.getElementById('connection').textContent.includes('Controller 1'));
  await phone.getByRole('button',{name:'Close profile',exact:true}).click();
  await phone.locator('[data-layer="isovist-btn"] input').check();
  await page.waitForFunction(()=>window.MR_ADAPTER.active['isovist-btn']);
  await phone.locator('[data-layer="isovist-btn"] .open').click();
  await phone.frameLocator('#dashboard').locator('#dashboard-content').waitFor();
  await phone.screenshot({path:'.runtime/phone-controls.png'});
  await phone.getByRole('button',{name:'Map',exact:true}).click();
  await phone.locator('#phone-map canvas.maplibregl-canvas').waitFor();
  await phone.waitForTimeout(1800);
  const box=await phone.locator('#phone-map').boundingBox();await phone.touchscreen.tap(box.x+box.width/2,box.y+box.height/2);
  await page.waitForFunction(()=>window.isovistSession.getState().position!==null);
  await phone.screenshot({path:'.runtime/phone-map.png'});
  await phone.getByRole('button',{name:'Open apps'}).click();
  await phone.locator('[data-layer="canvas-btn"] input').check();await phone.locator('[data-layer="canvas-btn"] .open').click();
  await phone.getByRole('button',{name:'Open drawing tools'}).click();await phone.locator('#tool').selectOption('marker');
  await phone.waitForFunction(()=>document.getElementById('layer-enabled').checked);
  const canvasBox=await phone.locator('#phone-map').boundingBox();
  await phone.touchscreen.tap(canvasBox.x+canvasBox.width*.5,canvasBox.y+canvasBox.height*.5);
  await page.waitForFunction(()=>window.MR_SESSION.getObjects().length===1);
  await phone.locator('#undo').click();await page.waitForFunction(()=>window.MR_SESSION.getObjects().length===0);
  await phone.locator('#redo').click();await page.waitForFunction(()=>window.MR_SESSION.getObjects().length===1);
  await phone.reload();await phone.waitForFunction(()=>document.getElementById('connection').textContent.includes('Controller 1'));
  await phone.screenshot({path:'.runtime/phone-drawer.png'});
  const admin=await desktop.newPage();await admin.goto(base+'/session/');await admin.locator('#qr img').waitFor();await admin.screenshot({path:'.runtime/admin.png'});
  const send=async(target,message)=>target.evaluate(message=>Object.values(window.__peers[0].connections).flat()[0].send(message),{actionId:crypto.randomUUID(),...message});
  const additional=[];
  for(let slot=2;slot<=5;slot++){
    const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});if(memoryTransport)await memoryTransport(context);
    const guest=await context.newPage();await guest.addInitScript(trackPeers);guest.on('pageerror',e=>errors.push(e.message));await guest.goto(url,{waitUntil:'domcontentloaded'});
    await guest.waitForFunction(()=>document.getElementById('connection').textContent.includes('Spectator'));
    if(slot<=4){await guest.locator('#choose-slot').click();await guest.locator('#slots button').nth(slot-1).click();await guest.waitForFunction(slot=>document.getElementById('connection').textContent.includes('Controller '+slot),slot);await guest.getByRole('button',{name:'Close profile',exact:true}).click();}
    additional.push({context,page:guest});
  }
  console.log('PASS: four editors and a fifth spectator');
  const objectId=await page.evaluate(()=>MR_SESSION.getObjects()[0].id);
  await send(additional[0].page,{type:'canvas',operation:'delete',objectId});
  await additional[0].page.getByText('Only the author or host can edit this annotation',{exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>MR_SESSION.getObjects().length),1);
  await send(additional[3].page,{type:'layer',layer:'canvas-btn',enabled:false});
  await additional[3].page.getByText('Choose an editing slot first',{exact:true}).waitFor();
  await send(phone,{type:'control',message:{type:'calibrate_action',action:'pan_up'}});
  await phone.getByText('Control is not available remotely',{exact:true}).waitFor();
  console.log('PASS: ownership, spectators and calibration boundary');
  await phone.locator('[data-layer="isovist-btn"] .open').click();
  await phone.frameLocator('#dashboard').locator('#isovist-radius').evaluate(input=>{input.value='250';input.dispatchEvent(new Event('input',{bubbles:true}));});
  await page.waitForFunction(()=>window.isovistSession.getState().radius===250);
  await additional[0].page.locator('[data-layer="isovist-btn"] .open').click();
  await additional[0].page.frameLocator('#dashboard').locator('#isovist-radius').waitFor();
  await additional[0].page.waitForFunction(()=>document.getElementById('dashboard').contentWindow.document.getElementById('isovist-radius')?.value==='250');
  const response=await phone.locator('#dashboard').evaluate(async iframe=>{const response=await iframe.contentWindow.fetch('/api/services/ecom/api/health');return {status:response.status,body:await response.json()};});
  assert.equal(response.status,200);assert.equal(response.body.status,'ok');
  console.log('PASS: authoritative settings and host-routed backend requests');
  await phone.getByRole('button',{name:'Open apps'}).click();
  await phone.locator('[data-layer="cfd-simulation-btn"] input').check();await phone.locator('[data-layer="cfd-simulation-btn"] .open').click();
  await phone.getByRole('button',{name:'Map',exact:true}).click();await phone.locator('#tool').selectOption('obstacle');
  await page.waitForFunction(()=>window.cfdSession.getState().active);
  const windBox=await phone.locator('#phone-map').boundingBox();
  for(const[x,y]of [[.44,.45],[.56,.45],[.56,.57]])await phone.touchscreen.tap(windBox.x+windBox.width*x,windBox.y+windBox.height*y);
  await phone.locator('#finish').click();await page.waitForFunction(()=>window.MR_CFD_OBSTACLES?.length===1);
  await phone.screenshot({path:'.runtime/phone-wind.png'});
  await send(phone,{type:'layer',layer:'cfd-simulation-btn',enabled:false});
  console.log('PASS: additive CFD obstacle drawing');
  await admin.getByRole('button',{name:'Pause editing',exact:true}).click();
  await phone.waitForFunction(()=>document.getElementById('connection').textContent.includes('paused'));
  await send(phone,{type:'canvas',operation:'delete',objectId});await phone.getByText('Host paused remote editing',{exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>MR_SESSION.getObjects().length),2);
  await admin.getByRole('button',{name:'Resume editing',exact:true}).click();
  const slot3=await page.evaluate(()=>MR_SESSION.getState().slots[2]);
  await page.evaluate(id=>{const c=new BroadcastChannel('mr_session_admin');c.postMessage({type:'admin-command',action:'release',personId:id});c.close();},slot3);
  await additional[3].page.locator('#choose-slot').click();await additional[3].page.locator('#slots button').nth(2).click();await additional[3].page.waitForFunction(()=>document.getElementById('connection').textContent.includes('Controller 3'));
  const sessionId=await page.evaluate(()=>MR_SESSION.getState().sessionId);await admin.close();
  const reopened=await desktop.newPage();await reopened.goto(base+'/session/');await reopened.locator('#qr img').waitFor();
  assert.equal(await page.evaluate(()=>MR_SESSION.getState().sessionId),sessionId);
  await page.waitForTimeout(500);const log=await(await page.request.get(base+'/api/session/'+sessionId)).json();
  assert.equal(log.schemaVersion,2);assert.equal(log.finalState.objects.length,2);assert.ok(log.events.some(e=>e.kind==='slot.released'));
  console.log('PASS: pause, release/reclaim, admin reopening and durable log');
  await phone.getByRole('button',{name:'Open apps'}).click();
  for(const id of ['cfd-simulation-btn','stormwater-btn','sun-study-btn','thermal-comfort-btn','isovist-btn','street-view-btn','epc-btn','ecom-energy-btn','bird-sounds-btn','slideshow-btn','campus-demo-btn','fcc-demo-btn','grid-animation-btn']){
    await phone.locator('[data-layer="'+id+'"] .open').click();
    await phone.frameLocator('#dashboard').locator('#dashboard-content').waitFor();
    await phone.waitForTimeout(200);
    await phone.screenshot({path:'.runtime/panel-'+id+'.png'});
    assert.equal(await phone.locator('#dashboard').evaluate(frame=>!!frame.contentWindow.document.querySelector('[data-target="calibrate-btn"]')),false);
    await phone.getByRole('button',{name:'Open apps'}).click();
  }
  console.log('PASS: all 13 dashboard panels and calibration UI exclusion');
  assert.equal(errors.length,0,errors.join('\n'));
  console.log('PASS: join, slot claim, layer control, Isovist tap, Canvas create/undo/redo, reload identity, admin QR');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
